# Generated by Django 4.2.4 on 2023-10-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
